Repository Team-Adaptar/manna-frontend, pull requests merged in 2021-05, with the labels that each got.

#5 DESIGN #3 - 메인 페이지 디자인 작업
  pages/index.vue
Labels: design

#11 SET #8 reset.css cdn 적용
  nuxt.config.js
Labels: setting

#12 frontend#1-회원가입 화면 구현
  package-lock.json
  package.json
  pages/join.vue
  yarn.lock
Labels: design

#16 SET #15-api 통신 환경설정
  package.json
  plugins/local-storage.js
  store/auth.js
Labels: setting

#20 DESIGN#18 - Frontend 퍼블리싱
  assets/fonts/BCcardB.otf
  assets/fonts/BCcardB.ttf
  assets/fonts/BCcardL.otf
  assets/fonts/BCcardL.ttf
  assets/imgaes/img_kakao_login_l.png
  assets/imgaes/img_kakao_login_m.png
  assets/kakao/kakao_login.png
  assets/scss/_base.scss
  assets/scss/_common.scss
  assets/scss/_components.scss
  assets/scss/_reset.scss
  assets/scss/main.scss
  assets/scss/reset.css
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/join.vue
  pages/login.vue
  tailwind.config.js
  yarn.lock
Labels: 🌆디자인
